### ISSUE TITLE
Load fails on Ubuntu 20.10

### ISSUE THREAD

**Issue by chgardener** [pcwii/cpkodi-skill#19]
I‘ve got Mycroft installed on Ubuntu 20.10 with Python 3.8.6. Mycroft runs without problems, but the installation of cpkodi fails with the following message:

```
Traceback (most recent call last):                                                                                              
  File "/home/rr/mycroft-core/mycroft/skills/skill_loader.py", line 276, in _load_skill_source                                  
    skill_module = load_skill_module(main_file_path, self.skill_id)                                                            
  File "/home/rr/mycroft-core/mycroft/skills/skill_loader.py", line 72, in load_skill_module                                    
    spec.loader.exec_module(mod)                                                                                               
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                      
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                 
  File "/opt/mycroft/skills/cpkodi-skill.pcwii/__init__.py", line 33, in <module>                                               
    for each_module in sys.modules:                                                                                            
RuntimeError: dictionary keys changed during iteration                                                                         
~~~~.840 | ERROR    | 56085 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill cpkodi-skill.pcwii failed to load
```

I have read [here](https://community.atlassian.com/t5/Jira-Core-questions/RuntimeError-dictionary-keys-changed-during-iteration-when/qaq-p/1245641) that a similar problem can be solved by switching from python3.8 to python3.7. Could I do this using a virtual environment?

**Comment by pcwii** [comment]
Honestly not sure about changing python version in a virtual environment. I would recommend checking with the myrcoft.ai forum they may be able to help. I will look into this error but it does look like it is related to python 3.8. I think mycroft only supports 2.7 currently. I'll watch the forum and see if I find anything in my testing.
